// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: learn.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const countLessonsByModule = `-- name: CountLessonsByModule :one
SELECT COUNT(*) as count
FROM lessons
WHERE module_id = ?1
`

func (q *Queries) CountLessonsByModule(ctx context.Context, moduleID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countLessonsByModule, moduleID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getGlossaryTerm = `-- name: GetGlossaryTerm :one
SELECT id, term, definition, category, created_at
FROM glossary_terms
WHERE term = ?1
`

func (q *Queries) GetGlossaryTerm(ctx context.Context, term string) (GlossaryTerm, error) {
	row := q.db.QueryRowContext(ctx, getGlossaryTerm, term)
	var i GlossaryTerm
	err := row.Scan(
		&i.ID,
		&i.Term,
		&i.Definition,
		&i.Category,
		&i.CreatedAt,
	)
	return i, err
}

const getLearningModule = `-- name: GetLearningModule :one
SELECT id, title, description, category, sort_order, created_at
FROM learning_modules
WHERE id = ?1
`

func (q *Queries) GetLearningModule(ctx context.Context, id string) (LearningModule, error) {
	row := q.db.QueryRowContext(ctx, getLearningModule, id)
	var i LearningModule
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Category,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getLesson = `-- name: GetLesson :one
SELECT id, module_id, title, content, summary, sort_order, created_at
FROM lessons
WHERE id = ?1
`

func (q *Queries) GetLesson(ctx context.Context, id string) (Lesson, error) {
	row := q.db.QueryRowContext(ctx, getLesson, id)
	var i Lesson
	err := row.Scan(
		&i.ID,
		&i.ModuleID,
		&i.Title,
		&i.Content,
		&i.Summary,
		&i.SortOrder,
		&i.CreatedAt,
	)
	return i, err
}

const getLessonsByModule = `-- name: GetLessonsByModule :many
SELECT id, module_id, title, content, summary, sort_order, created_at
FROM lessons
WHERE module_id = ?1
ORDER BY sort_order
`

func (q *Queries) GetLessonsByModule(ctx context.Context, moduleID string) ([]Lesson, error) {
	rows, err := q.db.QueryContext(ctx, getLessonsByModule, moduleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Lesson
	for rows.Next() {
		var i Lesson
		if err := rows.Scan(
			&i.ID,
			&i.ModuleID,
			&i.Title,
			&i.Content,
			&i.Summary,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomLearningTip = `-- name: GetRandomLearningTip :one
SELECT id, title, content, category, learn_url, active_date, created_at
FROM learning_tips
ORDER BY RANDOM()
LIMIT 1
`

func (q *Queries) GetRandomLearningTip(ctx context.Context) (LearningTip, error) {
	row := q.db.QueryRowContext(ctx, getRandomLearningTip)
	var i LearningTip
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Category,
		&i.LearnUrl,
		&i.ActiveDate,
		&i.CreatedAt,
	)
	return i, err
}

const getTodaysLearningTip = `-- name: GetTodaysLearningTip :one
SELECT id, title, content, category, learn_url, active_date, created_at
FROM learning_tips
WHERE active_date = DATE('now')
LIMIT 1
`

func (q *Queries) GetTodaysLearningTip(ctx context.Context) (LearningTip, error) {
	row := q.db.QueryRowContext(ctx, getTodaysLearningTip)
	var i LearningTip
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Category,
		&i.LearnUrl,
		&i.ActiveDate,
		&i.CreatedAt,
	)
	return i, err
}

const insertGlossaryTerm = `-- name: InsertGlossaryTerm :exec
INSERT INTO glossary_terms (id, term, definition, category, created_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    term=excluded.term,
    definition=excluded.definition,
    category=excluded.category
`

type InsertGlossaryTermParams struct {
	ID         string
	Term       string
	Definition string
	Category   string
	CreatedAt  time.Time
}

func (q *Queries) InsertGlossaryTerm(ctx context.Context, arg InsertGlossaryTermParams) error {
	_, err := q.db.ExecContext(ctx, insertGlossaryTerm,
		arg.ID,
		arg.Term,
		arg.Definition,
		arg.Category,
		arg.CreatedAt,
	)
	return err
}

const insertLearningModule = `-- name: InsertLearningModule :exec
INSERT INTO learning_modules (id, title, description, category, sort_order, created_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    title=excluded.title,
    description=excluded.description,
    category=excluded.category,
    sort_order=excluded.sort_order
`

type InsertLearningModuleParams struct {
	ID          string
	Title       string
	Description string
	Category    string
	SortOrder   int64
	CreatedAt   time.Time
}

func (q *Queries) InsertLearningModule(ctx context.Context, arg InsertLearningModuleParams) error {
	_, err := q.db.ExecContext(ctx, insertLearningModule,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.SortOrder,
		arg.CreatedAt,
	)
	return err
}

const insertLearningTip = `-- name: InsertLearningTip :exec
INSERT INTO learning_tips (id, title, content, category, learn_url, active_date, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    title=excluded.title,
    content=excluded.content,
    category=excluded.category,
    learn_url=excluded.learn_url,
    active_date=excluded.active_date
`

type InsertLearningTipParams struct {
	ID         string
	Title      string
	Content    string
	Category   string
	LearnUrl   sql.NullString
	ActiveDate sql.NullTime
	CreatedAt  time.Time
}

func (q *Queries) InsertLearningTip(ctx context.Context, arg InsertLearningTipParams) error {
	_, err := q.db.ExecContext(ctx, insertLearningTip,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Category,
		arg.LearnUrl,
		arg.ActiveDate,
		arg.CreatedAt,
	)
	return err
}

const insertLesson = `-- name: InsertLesson :exec
INSERT INTO lessons (id, module_id, title, content, summary, sort_order, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    module_id=excluded.module_id,
    title=excluded.title,
    content=excluded.content,
    summary=excluded.summary,
    sort_order=excluded.sort_order
`

type InsertLessonParams struct {
	ID        string
	ModuleID  string
	Title     string
	Content   string
	Summary   string
	SortOrder int64
	CreatedAt time.Time
}

func (q *Queries) InsertLesson(ctx context.Context, arg InsertLessonParams) error {
	_, err := q.db.ExecContext(ctx, insertLesson,
		arg.ID,
		arg.ModuleID,
		arg.Title,
		arg.Content,
		arg.Summary,
		arg.SortOrder,
		arg.CreatedAt,
	)
	return err
}

const listGlossaryTerms = `-- name: ListGlossaryTerms :many
SELECT id, term, definition, category, created_at
FROM glossary_terms
ORDER BY term
`

func (q *Queries) ListGlossaryTerms(ctx context.Context) ([]GlossaryTerm, error) {
	rows, err := q.db.QueryContext(ctx, listGlossaryTerms)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlossaryTerm
	for rows.Next() {
		var i GlossaryTerm
		if err := rows.Scan(
			&i.ID,
			&i.Term,
			&i.Definition,
			&i.Category,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlossaryTermsByCategory = `-- name: ListGlossaryTermsByCategory :many
SELECT id, term, definition, category, created_at
FROM glossary_terms
WHERE category = ?1
ORDER BY term
`

func (q *Queries) ListGlossaryTermsByCategory(ctx context.Context, category string) ([]GlossaryTerm, error) {
	rows, err := q.db.QueryContext(ctx, listGlossaryTermsByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlossaryTerm
	for rows.Next() {
		var i GlossaryTerm
		if err := rows.Scan(
			&i.ID,
			&i.Term,
			&i.Definition,
			&i.Category,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLearningModules = `-- name: ListLearningModules :many
SELECT id, title, description, category, sort_order, created_at
FROM learning_modules
ORDER BY category, sort_order
`

func (q *Queries) ListLearningModules(ctx context.Context) ([]LearningModule, error) {
	rows, err := q.db.QueryContext(ctx, listLearningModules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearningModule
	for rows.Next() {
		var i LearningModule
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLearningModulesByCategory = `-- name: ListLearningModulesByCategory :many
SELECT id, title, description, category, sort_order, created_at
FROM learning_modules
WHERE category = ?1
ORDER BY sort_order
`

func (q *Queries) ListLearningModulesByCategory(ctx context.Context, category string) ([]LearningModule, error) {
	rows, err := q.db.QueryContext(ctx, listLearningModulesByCategory, category)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearningModule
	for rows.Next() {
		var i LearningModule
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Category,
			&i.SortOrder,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLearningTips = `-- name: ListLearningTips :many
SELECT id, title, content, category, learn_url, active_date, created_at
FROM learning_tips
ORDER BY created_at DESC
LIMIT ?1
`

func (q *Queries) ListLearningTips(ctx context.Context, limit int64) ([]LearningTip, error) {
	rows, err := q.db.QueryContext(ctx, listLearningTips, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LearningTip
	for rows.Next() {
		var i LearningTip
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Category,
			&i.LearnUrl,
			&i.ActiveDate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchGlossaryTerms = `-- name: SearchGlossaryTerms :many
SELECT id, term, definition, category, created_at
FROM glossary_terms
WHERE term LIKE '%' || ?1 || '%'
   OR definition LIKE '%' || ?1 || '%'
ORDER BY term
`

func (q *Queries) SearchGlossaryTerms(ctx context.Context, query sql.NullString) ([]GlossaryTerm, error) {
	rows, err := q.db.QueryContext(ctx, searchGlossaryTerms, query)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlossaryTerm
	for rows.Next() {
		var i GlossaryTerm
		if err := rows.Scan(
			&i.ID,
			&i.Term,
			&i.Definition,
			&i.Category,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
