// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type CongressTrade struct {
	ID             string
	Member         string
	Party          sql.NullString
	Chamber        sql.NullString
	Symbol         string
	Action         string
	Amount         sql.NullString
	ExecutedAt     time.Time
	DisclosureDate time.Time
	Sentiment      float64
	SourceUrl      sql.NullString
}

type GlossaryTerm struct {
	ID         string
	Term       string
	Definition string
	Category   string
	CreatedAt  time.Time
}

type LearningModule struct {
	ID          string
	Title       string
	Description string
	Category    string
	SortOrder   int64
	CreatedAt   time.Time
}

type LearningTip struct {
	ID         string
	Title      string
	Content    string
	Category   string
	LearnUrl   sql.NullString
	ActiveDate sql.NullTime
	CreatedAt  time.Time
}

type Lesson struct {
	ID        string
	ModuleID  string
	Title     string
	Content   string
	Summary   string
	SortOrder int64
	CreatedAt time.Time
}

type NewsArticle struct {
	ID             string
	Title          string
	Source         string
	Summary        string
	SentimentScore float64
	Trend          string
	Tickers        string
	Url            string
	PublishedAt    time.Time
}

type Recommendation struct {
	ID         string
	Symbol     string
	Thesis     string
	Conviction string
	Score      float64
	Catalyst   sql.NullString
	CreatedAt  time.Time
}

type StockSnapshot struct {
	ID         string
	Symbol     string
	Name       string
	Sector     sql.NullString
	Industry   sql.NullString
	Change30   float64
	Change90   float64
	Change365  float64
	VsSp50030  float64
	VsSp50090  float64
	VsSp500365 float64
	Conviction string
	Thesis     string
	UpdatedAt  time.Time
}
