// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: news.sql

package database

import (
	"context"
	"time"
)

const insertNewsArticle = `-- name: InsertNewsArticle :exec
INSERT INTO news_articles (id, title, source, summary, sentiment_score, trend, tickers, url, published_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    title=excluded.title,
    source=excluded.source,
    summary=excluded.summary,
    sentiment_score=excluded.sentiment_score,
    trend=excluded.trend,
    tickers=excluded.tickers,
    url=excluded.url,
    published_at=excluded.published_at
`

type InsertNewsArticleParams struct {
	ID             string
	Title          string
	Source         string
	Summary        string
	SentimentScore float64
	Trend          string
	Tickers        string
	Url            string
	PublishedAt    time.Time
}

func (q *Queries) InsertNewsArticle(ctx context.Context, arg InsertNewsArticleParams) error {
	_, err := q.db.ExecContext(ctx, insertNewsArticle,
		arg.ID,
		arg.Title,
		arg.Source,
		arg.Summary,
		arg.SentimentScore,
		arg.Trend,
		arg.Tickers,
		arg.Url,
		arg.PublishedAt,
	)
	return err
}

const listLatestNews = `-- name: ListLatestNews :many
SELECT id, title, source, summary, sentiment_score, trend, tickers, url, published_at
FROM news_articles
ORDER BY published_at DESC
LIMIT ?1
`

func (q *Queries) ListLatestNews(ctx context.Context, limit int64) ([]NewsArticle, error) {
	rows, err := q.db.QueryContext(ctx, listLatestNews, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NewsArticle
	for rows.Next() {
		var i NewsArticle
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Source,
			&i.Summary,
			&i.SentimentScore,
			&i.Trend,
			&i.Tickers,
			&i.Url,
			&i.PublishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
