// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recommendations.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const insertRecommendation = `-- name: InsertRecommendation :exec
INSERT INTO recommendations (id, symbol, thesis, conviction, score, catalyst, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    symbol=excluded.symbol,
    thesis=excluded.thesis,
    conviction=excluded.conviction,
    score=excluded.score,
    catalyst=excluded.catalyst,
    created_at=excluded.created_at
`

type InsertRecommendationParams struct {
	ID         string
	Symbol     string
	Thesis     string
	Conviction string
	Score      float64
	Catalyst   sql.NullString
	CreatedAt  time.Time
}

func (q *Queries) InsertRecommendation(ctx context.Context, arg InsertRecommendationParams) error {
	_, err := q.db.ExecContext(ctx, insertRecommendation,
		arg.ID,
		arg.Symbol,
		arg.Thesis,
		arg.Conviction,
		arg.Score,
		arg.Catalyst,
		arg.CreatedAt,
	)
	return err
}

const listRecommendations = `-- name: ListRecommendations :many
SELECT id, symbol, thesis, conviction, score, catalyst, created_at
FROM recommendations
ORDER BY score DESC
LIMIT ?1
`

func (q *Queries) ListRecommendations(ctx context.Context, limit int64) ([]Recommendation, error) {
	rows, err := q.db.QueryContext(ctx, listRecommendations, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Recommendation
	for rows.Next() {
		var i Recommendation
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Thesis,
			&i.Conviction,
			&i.Score,
			&i.Catalyst,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
