// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stocks.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const insertStockSnapshot = `-- name: InsertStockSnapshot :exec
INSERT INTO stock_snapshots (
    id, symbol, name, sector, industry, change_30, change_90, change_365,
    vs_sp500_30, vs_sp500_90, vs_sp500_365, conviction, thesis, updated_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET
    symbol=excluded.symbol,
    name=excluded.name,
    sector=excluded.sector,
    industry=excluded.industry,
    change_30=excluded.change_30,
    change_90=excluded.change_90,
    change_365=excluded.change_365,
    vs_sp500_30=excluded.vs_sp500_30,
    vs_sp500_90=excluded.vs_sp500_90,
    vs_sp500_365=excluded.vs_sp500_365,
    conviction=excluded.conviction,
    thesis=excluded.thesis,
    updated_at=excluded.updated_at
`

type InsertStockSnapshotParams struct {
	ID         string
	Symbol     string
	Name       string
	Sector     sql.NullString
	Industry   sql.NullString
	Change30   float64
	Change90   float64
	Change365  float64
	VsSp50030  float64
	VsSp50090  float64
	VsSp500365 float64
	Conviction string
	Thesis     string
	UpdatedAt  time.Time
}

func (q *Queries) InsertStockSnapshot(ctx context.Context, arg InsertStockSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, insertStockSnapshot,
		arg.ID,
		arg.Symbol,
		arg.Name,
		arg.Sector,
		arg.Industry,
		arg.Change30,
		arg.Change90,
		arg.Change365,
		arg.VsSp50030,
		arg.VsSp50090,
		arg.VsSp500365,
		arg.Conviction,
		arg.Thesis,
		arg.UpdatedAt,
	)
	return err
}

const listStockSnapshots = `-- name: ListStockSnapshots :many
SELECT id, symbol, name, sector, industry, change_30, change_90, change_365,
       vs_sp500_30, vs_sp500_90, vs_sp500_365, conviction, thesis, updated_at
FROM stock_snapshots
ORDER BY vs_sp500_90 DESC
LIMIT ?1
`

func (q *Queries) ListStockSnapshots(ctx context.Context, limit int64) ([]StockSnapshot, error) {
	rows, err := q.db.QueryContext(ctx, listStockSnapshots, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StockSnapshot
	for rows.Next() {
		var i StockSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.Symbol,
			&i.Name,
			&i.Sector,
			&i.Industry,
			&i.Change30,
			&i.Change90,
			&i.Change365,
			&i.VsSp50030,
			&i.VsSp50090,
			&i.VsSp500365,
			&i.Conviction,
			&i.Thesis,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
